import { getAuthConfigProvider } from "@convex-dev/better-auth/auth-config";
import type { AuthConfig } from "convex/server";

// Tells Convex which JWT issuer to trust. Generated by the Better Auth
// component using the current deployment's site URL — no manual provider
// boilerplate needed.
export default {
  providers: [getAuthConfigProvider()],
} satisfies AuthConfig;
